version: '3'
services: 
    app:
        container_name: web_cgi
        build:
            context: .
        volumes:
            - ./environment:/var/www
            - ./log/web:/var/log/nginx/web
        ports:
            - "8080:80"